Add files to repository
obed300/learn-to-review pull request #1
Opened 2023-01-20 16:39 UTC by obed300

This pull request is been created so that my coding partner can review the 'to-do list' project

2023-01-24 07:04 UTC, shasherazi requested changes
Your code follows almost all the best practices, including YAGNI, DRY, and KISS. I left some comments where I found room for improvement.

2023-01-24 07:04 UTC, shasherazi commented on src/index.js
> +  UI.addtodo(mylist);
I think it would be better to use `camelCase` or `snake_case` for better readability. For example, `listLibrary` and `addTodo`.

2023-01-24 07:04 UTC, shasherazi commented on src/modules/completed.js
> +        data.completed = false;
Can you explain these lines of code? You are checking if the task is completed and then setting it to false, why? Or maybe I misunderstood how it is working? Please explain this a bit.

2023-01-24 17:40 UTC, obed300 commented on src/index.js
> +  UI.addtodo(mylist);
Sure I will do that. Thank you

2023-01-24 21:16 UTC, obed300 commented on src/modules/completed.js
> +        data.completed = false;
Sure I will😊. This is a conditional statement used to check if the index of the current item matches the index passed as a parameter to the function. If the index matches, the function checks the "completed" property of the item. If the property is set to "true", it sets it to "false" to mark the task as incomplete. If the property is set to "false", it sets it to "true" to mark the task as completed. In simple terms, it helps in toggling  the completed status.

2023-01-26 07:35 UTC, shasherazi commented on src/modules/completed.js
> +        data.completed = false;
Oh, ok, now I understand. Thanks for the explanation

2023-01-27 08:33 UTC, shasherazi approved these changes

2023-01-27 08:50 UTC, merged